name: list_load_more
description: A lazy loading ListView easy to implementation, easy to customize with your own loading animation and support some feature like add, remove single item and focus to item
version: 1.0.1
homepage: https://github.com/tuannvm2109/list_load_more

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
